// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(marketing)/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/certification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certification">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/certification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/coaches/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coaches/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/coaches/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/coaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coaches">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/coaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tenant)/sites/[tenant]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sites/[tenant]/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(tenant)/sites/[tenant]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tenant)/sites/[tenant]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sites/[tenant]">> = Specific
  const handler = {} as typeof import("../../src/app/(tenant)/sites/[tenant]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/certifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/certifications">> = Specific
  const handler = {} as typeof import("../../src/app/account/certifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/chapters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/chapters">> = Specific
  const handler = {} as typeof import("../../src/app/account/chapters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/coaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/coaches">> = Specific
  const handler = {} as typeof import("../../src/app/account/coaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/content">> = Specific
  const handler = {} as typeof import("../../src/app/account/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/account/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/dues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/dues">> = Specific
  const handler = {} as typeof import("../../src/app/account/dues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/profile">> = Specific
  const handler = {} as typeof import("../../src/app/account/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/register-chapter-head/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/register-chapter-head">> = Specific
  const handler = {} as typeof import("../../src/app/account/register-chapter-head/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/register-coach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/register-coach">> = Specific
  const handler = {} as typeof import("../../src/app/account/register-coach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/account/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/chapter/coaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/chapter/coaches">> = Specific
  const handler = {} as typeof import("../../src/app/admin/chapter/coaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/chapter/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/chapter/events">> = Specific
  const handler = {} as typeof import("../../src/app/admin/chapter/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/chapter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/chapter">> = Specific
  const handler = {} as typeof import("../../src/app/admin/chapter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/chapter/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/chapter/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/chapter/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/global/chapters/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/global/chapters/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/global/chapters/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/global/chapters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/global/chapters">> = Specific
  const handler = {} as typeof import("../../src/app/admin/global/chapters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/global/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/global">> = Specific
  const handler = {} as typeof import("../../src/app/admin/global/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/coaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/coaches">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/coaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chapters/provision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chapters/provision">> = Specific
  const handler = {} as typeof import("../../src/app/api/chapters/provision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/save-draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/save-draft">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/save-draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/update">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/embed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/embed">> = Specific
  const handler = {} as typeof import("../../src/app/api/embed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/sign-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/sign-out">> = Specific
  const handler = {} as typeof import("../../src/app/auth/sign-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(tenant)/sites/[tenant]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sites/[tenant]">> = Specific
  const handler = {} as typeof import("../../src/app/(tenant)/sites/[tenant]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/chapter/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/chapter">> = Specific
  const handler = {} as typeof import("../../src/app/admin/chapter/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/global/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/global">> = Specific
  const handler = {} as typeof import("../../src/app/admin/global/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
